#今からdocker-compose書きますって宣言

version: "3"

volumes:
  db-data:

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/cloud"
    tty: true
    stdin_open: true
    depends_on:
      - localhost
    links:
      - localhost

  localhost:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"