version: "3"

volumes:
  db-data:

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/cloud"
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"     
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "db-data:/var/lib/postgresql/data"