
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  #defaltuser
  user: postgres
  #defaultport
  port: 5432
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rubymania_development

test:
  <<: *default
  database: rubymania_test

production:
  <<: *default
  database: rubymania_production
  username: rubymania
  password: <%= ENV['RAILS_DOCKER_DATABASE_PASSWORD'] %>
